plugins {
    id 'java'
}

group 'com.starkbank.ellipticcurve'
version '1.1.0'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}
dependencies {
    testImplementation 'junit:junit:4.13.2'
}

test {
    testLogging {
        events "passed", "failed", "skipped"
        showExceptions true
        showCauses true
        showStackTraces true
        exceptionFormat "full"
    }
}

archivesBaseName = "starkbank-ecdsa"


task javadocJar(type: Jar) {
    archiveClassifier = 'javadoc'
    from javadoc
}

task sourcesJar(type: Jar) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives javadocJar, sourcesJar
}
